DEEPSORT:
  #REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7"
  REID_CKPT: "./deep_sort/deep/checkpoint/model_140.pt"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.5
  NMS_MAX_OVERLAP: 0.9
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
